### ISSUE TITLE
Core.lua error

### ISSUE THREAD

**Issue by blehmonster** [AlexOvares/Personal-Black-List-PBL#5]
Hi there,

Thanks for making this addon.  I also posted this over at Curseforge before I noticed you had a github.  Please forgive me for the duplicate filing, and I hope you can solve the issue.  Thanks!

1x PersonalBlacklist/Core.lua:432: attempt to call method 'GetUnit' (a nil value)
[string "@PersonalBlacklist/Core.lua"]:432: in function <PersonalBlacklist/Core.lua:431>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@HandyNotes_DragonflightTreasures/handler/handler.lua"]:957: in function <...HandyNotes_DragonflightTreasures/handler/handler.lua:773>
[string "=(tail call)"]: ?
[string "@HandyNotes_DragonflightTreasures/handler/handler.lua"]:1030: in function <...HandyNotes_DragonflightTreasures/handler/handler.lua:1006>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:166: in function `OnEnter'
[string "@HandyNotes/HandyNotes.lua"]:399: in function <HandyNotes/HandyNotes.lua:398>

Locals:
tooltip = HandyNotes_DragonflightTreasuresComparisonTooltip {
0 = <userdata>
SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetHyperlink = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
SetSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetItemInteractionItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetBuybackItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetWeeklyReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
BottomOverlay = Texture {
}
SetSpellByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:293
NineSlice = Frame {
}
SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
info = <table> {
}
updateTooltipTimer = 0.200000
SetLootRollItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
InternalProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:240
SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetBagItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
TextRight1 = HandyNotes_DragonflightTreasuresComparisonTooltipTextRight1 {
}
SetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetLineDataAttribute = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:232
SetAchievementByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetInventoryItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetCurrencyByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetQuestLogCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetBagItemChild = <functi

**Comment by Scryrz** [comment]
Hi @blehmonster - thanks for the report! I'll look into this as soon as I can. It's a conflict between PBL and Handynotes.

**Comment by Scryrz** [comment]
**Update:** Fixed as of version 3.7.7. Closing this, but if you run into this issue again for some reason feel free to re-open.
